### ISSUE TITLE
Install failed due to issue with dependency

### ISSUE THREAD

**Issue by simevidas** [Munter/hyperlink#6]
I tried to install your tool but got an error (see screenshot). It looks like one of your dependencies requires Python which isn’t pre-installed on Windows (not sure about OS X). Can you make sense of this?

![capture](https://cloud.githubusercontent.com/assets/716405/6999696/df442d08-dc11-11e4-88df-c26616a2d95c.PNG)

**Comment by Munter** [comment]
It's a known issue. I have this dependency chain that leads to the failure:
`hyperlink --> assetgraph --> jdsom --> contextify`

Contextify uns a local compile step on install, which is what in turn requires python and probably also a C++ compiler.

There are instructions how to make it work here at [https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide](https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide), though I have not checked this myself, and I haven't had enough feedback from windows user to know if it's stable.

Later versions of jsdom don't require contextify, so we can probably eliminate that compile step in the future. We are working on the [upgradeJsdom](https://github.com/assetgraph/assetgraph/tree/upgradeJsdom) branch of assetgraph to make it compatible with the later versions. We don't have a deadline for when this is going to hit master, since this is all happening in limited spare time.

**Comment by simevidas** [comment]
Thanks for the insight :)
